spring.application.name=mountain-tracker

spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/mountain_tracker}

server.port=${PORT:3000}

spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false
spring.data.mongodb.auto-index-creation=true